dataset:
  root: "./dataset"
  version: "v1.14"
  load: False

client:
  host: 127.0.0.1
  port: 2000
  time_out: 10.0

sensors:
  !include ./configs/sensors.yaml

categories:
  !include ./configs/categories.yaml

attributes:
  !include ./configs/attributes.yaml

visibility:
  !include ./configs/visibility.yaml 

worlds:  #map
  - 
    map_name: "Town03"
    map_category: "semantic_prior"
    settings:
      fixed_delta_seconds: 0.01 
    captures: #log
      - 
        date: "2023-01-09"
        time: "10-45-20"
        timezone: "+0800"
        capture_vehicle: "c0003"
        location: "chengdu"
        collect_time: 30
        scenes:
          - 
            weather_mode: "custom"
            weather:
              cloudiness: 0 # Values range from 0 to 100, being 0 a clear sky and 100 one completely covered with clouds.
              precipitation: 0 # Rain intensity values range from 0 to 100, being 0 none at all and 100 a heavy rain.
              precipitation_deposits: 0 # Determines the creation of puddles. Values range from 0 to 100, being 0 none at all and 100 a road completely capped with water. Puddles are created with static noise, meaning that they will always appear at the same locations.
              wind_intensity: 0 # Controls the strength of the wind with values from 0, no wind at all, to 100, a strong wind. The wind does affect rain direction and leaves from trees, so this value is restricted to avoid animation issues.
              sun_azimuth_angle: 0 # The azimuth angle of the sun. Values range from 0 to 360. Zero is an origin point in a sphere determined by Unreal Engine.
              sun_altitude_angle: 90 # Altitude angle of the sun. Values range from -90 to 90 corresponding to midnight and midday each.
              fog_density: 0 # Fog concentration or thickness. It only affects the RGB camera sensor. Values range from 0 to 100.
              fog_distance: 0 # Fog start distance. Values range from 0 to infinite.
              wetness: 0 # Wetness intensity. It only affects the RGB camera sensor. Values range from 0 to 100.
              fog_falloff: 0 # Density of the fog (as in specific mass) from 0 to infinity. The bigger the value, the more dense and heavy it will be, and the fog will reach smaller heights. Corresponds to Fog Height Falloff in the UE docs.If the value is 0, the fog will be lighter than air, and will cover the whole scene.A value of 1 is approximately as dense as the air, and reaches normal-sized buildings.For values greater than 5, the air will be so dense that it will be compressed on ground level.
              scattering_intensity: 0 # Controls how much the light will contribute to volumetric fog. When set to 0, there is no contribution.
              mie_scattering_scale: 0 # Controls interaction of light with large particles like pollen or air pollution resulting in a hazy sky with halos around the light sources. When set to 0, there is no contribution.
              rayleigh_scattering_scale: 0.0331 # Controls interaction of light with small particles like air molecules. Dependent on light wavelength, resulting in a blue sky in the day or red sky in the evening.
              dust_storm: 0 # Determines the strength of the dust storm weather. Values range from 0 to 100.
            ego_vehicle:
              bp_name: "vehicle.tesla.model3"
              location: 
                x: -80.62303161621094
                y: 27.47465705871582
                z: 0.5999999642372131
              rotation: 
                yaw: 0.15919798612594604
                pitch: 0.0
                roll: 0.0
              options: ~
              path: 
                - 
                  x: -89.62303161621094
                  y: 16.47465705871582
                  z: 0.5999999642372131
            vehicles:
              !include ./configs/vehicles.yaml
            walkers:
              !include ./configs/walkers.yaml
            calibrated_sensors:
              !include ./configs/calibrated_sensors.yaml
            description:
              "test"

