- 
  bp_name: "vehicle.tesla.model3"
  location:
    x: -70.25457000732422
    y: 27.96375846862793
    z: 0.5999999642372131
  rotation:
    yaw: -90
    pitch: 0
    roll: 0
  path:
    - x: -87.62303161621094
      y: 12.967159271240234
      z: 0.5999999642372131
