#-------------------visibility----------------
- 
  description: "visibility of whole object is between 0 and 40%"
  level: "v0-40"
    
-
  description: "visibility of whole object is between 40 and 60%"
  level: "v40-60"
    
-
  description: "visibility of whole object is between 60 and 80%"
  level: "v60-80"
    
-
  description: "visibility of whole object is between 80 and 100%"
  level: "v80-100"
  